### ISSUE TITLE
Offer a way to provide preferred GPU in case of multi-GPU setups

### ISSUE THREAD

**Issue by awerlang** [mviereck/x11docker#483]
Sample inxi output:

```
$ inxi -G
Graphics:
  Device-1: Intel HD Graphics 630 driver: i915 v: kernel
  Device-2: NVIDIA GP107 [GeForce GTX 1050 Ti] driver: nvidia v: 525.85.05
  Display: x11 server: X.Org v: 21.1.6 driver: X: loaded: modesetting,nvidia
    dri: iris gpu: i915 resolution: 1: 2560x1440~60Hz 2: 2560x1440~60Hz
  API: OpenGL v: 4.6 Mesa 22.3.4 renderer: Mesa Intel HD Graphics 630 (KBL
    GT2)
```

In this setup, NVIDIA is available but only Intel is used by Xorg. Some options:

- `--gpu=xorg`: share device used by xorg
- `--gpu=intel`: share intel device
- `--gpu=dri`: share DRI devices

**Reproduction:**

Execute x11docker with `--gpu` flag.

**Observed behavior:**

NVIDIA devices are probed, attempted to be installed.

**Expected behavior:**

Ignore NVIDIA even though NVIDIA proprietary drivers are installed.

**Comment by awerlang** [comment]
During some tests with sway, I found that containerized software can still query loaded kernel drivers. I ended up removing proprietary driver and blacklisting nouveau, but it could also work by masking `/proc/driver/nvidia`.

**Comment by awerlang** [comment]
I switched Xorg to leverage nvidia with proprietary drivers again (no xorg.conf):

```
$ inxi -G
Graphics:
  Device-1: Intel HD Graphics 630 driver: i915 v: kernel
  Device-2: NVIDIA GP107 [GeForce GTX 1050 Ti] driver: nvidia v: 525.85.05
  Device-3: Logitech HD Pro Webcam C920 type: USB
    driver: snd-usb-audio,uvcvideo
  Display: x11 server: X.Org v: 21.1.6 driver: X: loaded: modesetting,nvidia
    unloaded: fbdev,vesa dri: iris gpu: i915 resolution: 1: 2560x1440~60Hz
    2: 2560x1440~60Hz
  API: OpenGL v: 4.6.0 NVIDIA 525.85.05 renderer: NVIDIA GeForce GTX 1050
    Ti/PCIe/SSE2
```

I have commented out paths in x11docker which attempt to prepare nvidia stuff and ran with `--security-opt mask=/proc/driver` but it doesn't seem to be enough.

Base command line:

```
x11docker --backend=podman --xc --cap-default --newprivileges=no --init=systemd --home --network --clipboard --webcam --pulseaudio=host --gpu --xorg -- --security-opt mask=/proc/driver -- awerlang/citrix
```

--xpra-xwayland fails

```
(xpra:141): Gdk-ERROR **: 13:22:31.608: The program 'xpra' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadContext'.
  (Details: serial 270 error_code 158 request_code 152 (GLX) minor_code 6)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap (core dumped)

xterm: fatal IO error 104 (Connection reset by peer) or KillClient on X server ":105"
```

--nxagent is able to launch xterm but firefox fails with a segmentation fault

--xorg fails

```
(EE) xf86OpenConsole: Cannot open virtual console 8 (Permission denied)
```

--hostdisplay fails

```
Invalid MIT-MAGIC-COOKIE-1 key
Authorization required, but no authorization protocol specified
```

In fact, only `--nxagent` works if I remove `--gpu`, other options fail to launch.

TLDR; I'd like to use i915 inside container independently of what Xorg's running.
